# Generated by Django 4.2 on 2023-04-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AcoountApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAddProduct',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static')),
                ('description', models.TextField(max_length=500)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Dom', models.DateField()),
                ('Doe', models.DateField()),
                ('user', models.ManyToManyField(to='AcoountApp.pharmacyprofile')),
            ],
        ),
    ]
